#!/usr/bin/python
import sys
from mediasys.command import MediasysCommand, CliError

DESCR = """\
Updates repository metadata for a distribution and or/media.
"""

class Put(MediasysCommand):

    usage = "%prog -d DISTRO [-m MEDIA]"
    descr = DESCR

    def init_parser(self, parser):
        MediasysCommand.init_parser(self, parser)
        parser.add_option("-d", "--distro", type="str", default=None,
                help="target distribution")
        parser.add_option("-m", "--media", type="str", default=None,
                help="target media")

    def run(self):
        if self.args:
            raise CliError("no args expected")
        self.mediasys.update(distro=self.opts.distro,
                media=self.opts.media)

Put().main()

# vim:ts=4:sw=4:et
